### PR TITLE
Prevent array from crossing boundaries

### PR DESCRIPTION
**Pull request by 01Hank**

### CODE REVIEW

**Comment by felipejfc** [comment]
Did you actually hit this state? It should never happen

**Comment by 01Hank** [comment]
yes! It crashed when I tried using Python 2.7 as a client request service，
This occurs in the first data packet after I processed the shake and ack messages，
So in order to avoid game crashes, I think we should do a boundary check here





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "topfreegames/pitaya"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月26日(星期六) 凌晨1:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR #334)





 
Did you actually hit this state? It should never happen

**Comment by felipejfc** [comment]
Can you add a test case for this scenario?

**Comment by 01Hank** [comment]
Unfortunately, we cannot provide you with this test code
Because this serialization code is confidential to the company

Here is a variant of JSON
It reduces the ascii field range of JSON
An error occurred while deserializing this encoding








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "topfreegames/pitaya"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月6日(星期三) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR #334)





 
Can you add a test case for this scenario?

**Comment by felipejfc** [comment]
no need to use your specific code. Just invent/come up with a case that will trigger the scenario you want to avoid

**Comment by 01Hank** [comment]
As shown in the figure, I did construct an illegal data packet. When constructing the length of the packet header, I used the length of the real data, which caused the array to overrun and crash when the server reads the data.



---Original---
From: "Felipe ***@***.***&gt;
Date: Thu, Sep 7, 2023 03:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR#334)




 
no need to use your specific/proprietary code. Just invent/come up with a case that will trigger the scenario you want to avoid

**Comment by 01Hank** [comment]
I think this could be a means of attack.




---Original---
From: "Felipe ***@***.***&gt;
Date: Thu, Sep 7, 2023 03:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR#334)




 
no need to use your specific/proprietary code. Just invent/come up with a case that will trigger the scenario you want to avoid

**Comment by haoyu234** [comment]
Several ways have been tested to cause abnormal exits.

1. Illegal ID (Incomplete packets)
```go
func main() {
	data := []uint8{0,129,129,129,129,129}
	println(message.Decode(data))
}
```
```shell
panic: runtime error: slice bounds out of range [:131] with capacity 6

goroutine 1 [running]:
github.com/topfreegames/pitaya/v2/conn/message.Decode({0xc0000180b8, 0x6, 0x6})
	/root/go/pkg/mod/github.com/topfreegames/pitaya/v2@v2.6.1/conn/message/message_encoder.go:180 +0x6ad
main.main()
	/root/repos/tank/main.go:40 +0xa7
```
2. Illegal route length
```golang
func main() {
	data := []uint8{0,1,100,115,116,104,34,34}
	println(message.Decode(data))
}
```
```shell
panic: runtime error: slice bounds out of range [:103] with capacity 8

goroutine 1 [running]:
github.com/topfreegames/pitaya/v2/conn/message.Decode({0xc0000180b8, 0x8, 0x8})
	/root/go/pkg/mod/github.com/topfreegames/pitaya/v2@v2.6.1/conn/message/message_encoder.go:180 +0x6ad
main.main()
	/root/repos/tank/main.go:72 +0xbd
```
3.  Incomplete packets
```golang
func main() {
	data := []uint8{1,1,34}
	println(message.Decode(data))
}
```
```shell
panic: runtime error: slice bounds out of range [:4] with capacity 3

goroutine 1 [running]:
github.com/topfreegames/pitaya/v2/conn/message.Decode({0xc0000180b8, 0x3, 0x3})
	/root/go/pkg/mod/github.com/topfreegames/pitaya/v2@v2.6.1/conn/message/message_encoder.go:167 +0x6c5
main.main()
	/root/repos/tank/main.go:72 +0x86
```

**Comment by haoyu234** [comment]
It seems that all the use of the offset variable needs to do a range check. Add checks for other code paths as well.
似乎所有使用到offset变量的地方都需要做范围检查. 把其他代码路径的检查也加一下吧 @01Hank

**Comment by 01Hank** [comment]
好的



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 7, 2023 11:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR#334)




 
It seems that all the use of the offset variable needs to do a range check. Add checks for other code paths as well.
 似乎所有使用到offset变量的地方都需要做范围检查. 把其他代码路径的检查也加一下吧 @01Hank

**Comment by 01Hank** [comment]
因为我这边某个服务要用Python做所以在接包的时候遇到这个问题了



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 7, 2023 11:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR#334)




 
It seems that all the use of the offset variable needs to do a range check. Add checks for other code paths as well.
 似乎所有使用到offset变量的地方都需要做范围检查. 把其他代码路径的检查也加一下吧 @01Hank

**Comment by felipejfc** [comment]
> It seems that all the use of the offset variable needs to do a range check. Add checks for other code paths as well. 似乎所有使用到offset变量的地方都需要做范围检查. 把其他代码路径的检查也加一下吧 @01Hank

mind doing a PR for these cases?

**Comment by 01Hank** [comment]
ok



---Original---
From: "Felipe ***@***.***&gt;
Date: Sat, Sep 9, 2023 02:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topfreegames/pitaya] Prevent array from crossing boundaries (PR#334)




  
It seems that all the use of the offset variable needs to do a range check. Add checks for other code paths as well. 似乎所有使用到offset变量的地方都需要做范围检查. 把其他代码路径的检查也加一下吧 @01Hank
  
mind doing a PR for these cases?

**Comment by 01Hank** [comment]
> 
I have submitted the new changes

**Review by felipejfc — APPROVED** [review]

**Pull request closed without merging**
