### PR TITLE
allow to customize the timeout of rpc

### PR DESCRIPTION
**Pull request by bruce1125**
To customize the timeout value, the only thing we need to do is just like the code below before RPC call and then use the ctx as the context argument:
`
ctx := pcontext.AddToPropagateCtx(context.Background(), constants.RequestTimeout, (60 * time.Second).String())
`

### CODE REVIEW

**Comment by rsafonseca** [comment]
Hey @bruce1125 , what are you trying to achieve exactly? The timeout for the RPCs can already be configured via "pitaya.cluster.rpc.client.grpc.requesttimeout" or "pitaya.cluster.rpc.client.nats.requesttimeout" config options :)

**Comment by bruce1125** [comment]
> Hey @bruce1125 , what are you trying to achieve exactly? The timeout for the RPCs can already be configured via "pitaya.cluster.rpc.client.grpc.requesttimeout" or "pitaya.cluster.rpc.client.nats.requesttimeout" config options :)

Thank you for review. Although we can configure the grpc/nats timeout, that is global. It can cover most of cases excluding some time-consuming operations, such as getting an external API response, collecting a cpu/memory snapshot, etc. And I don't want to set the timeout value only for these issues..

**Review by felipejfc — APPROVED** [review]
Sounds like a valid use case. Will be merging it

**Comment by felipejfc** [comment]
@bruce1125 would appreciate if you could update the docs later covering this new capability

**Comment by bruce1125** [comment]
> @bruce1125 would appreciate if you could update the docs later covering this new capability

@felipejfc It's my pleasure,I've created a new [PR](https://github.com/topfreegames/pitaya/pull/393#issue-2260613481).
I am not sure is it OK,and I am realy happy to discuss with you guys if there is any problem.

**Pull request merged**
