### PR TITLE
Feature/custom metrics

### PR DESCRIPTION
**Pull request by Henrod**
Possibility to add custom metrics on starting application. The danger in this is that a wrong config will cause the app to crash because the prometheus lib crashes.

### CODE REVIEW

**Comment by andrehp** [comment]
Could you describe a little better how to use the custom metrics? The configuration values are not very clear for me

**Comment by Henrod** [comment]
I don't know if doc is the better choice for this, maybe add an example?

**Comment by andrehp** [comment]
Yeah, I guess an example would already help

**Comment by Henrod** [comment]
@andrehp I made an example

**Comment by andrehp** [comment]
Nice, could you just add a small paragraph to the docs mentioning custom metrics?

https://github.com/topfreegames/pitaya/blob/master/docs/features.md#monitoring

**Comment by Henrod** [comment]
@andrehp do you think this is enough?

**Comment by andrehp** [comment]
Yeah, LGTM

I'm gonna merge this, good job!

**Pull request merged**
